name: techviz
description: TechViz

dependencies:
  flutter:
    sdk: flutter
  test: ^1.5.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: 0.12.0
  shared_preferences: ^0.4.2
  sqflite: any
  event_bus: ^1.0.1
  intl: ^0.15.7
  flutter_is_emulator: ^1.0.0
  charts_flutter: 0.5.0
  observable: any
  flushbar: 1.7.0
  package_info: ^0.4.0
  fluttertoast: ^3.0.1
  swipedetector: ^1.2.0
  dart_amqp: ^0.1.0
  flutter_slidable: ^0.5.0
  flutter_typeahead: ^1.5.0
  mockito: ^4.0.0
  kiwi: ^0.2.0
  rxdart: ^0.22.0
  animator: ^0.1.3
  auto_size_text: ^2.0.1
  datetime_picker_formfield: ^0.4.1
  validators: ^2.0.0+1
  device_info: ^0.4.0
  uuid: ^2.0.2
  path_provider: ^1.2.0
  connectivity: ^0.4.3+7

  mqtt_client:
    git: git@git.internal.bis2.net:Mobile/Plugins/mqtt_client.git


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

#  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/json/config.json
    - assets/images/ic_about.png
    - assets/images/ic_alert.png
    - assets/images/ic_available_machine.png
    - assets/images/ic_down_arrow.png
    - assets/images/ic_duration.png
    - assets/images/ic_help.png
    - assets/images/ic_in_use.png
    - assets/images/ic_logout.png
    - assets/images/ic_my_profile.png
    - assets/images/ic_new_note.png
    - assets/images/ic_no_connection.png
    - assets/images/ic_note.png
    - assets/images/ic_offline_machine.png
    - assets/images/ic_out_of_service.png
    - assets/images/ic_processing.png
    - assets/images/ic_reserve.png
    - assets/images/ic_search.png
    - assets/images/bg_splash.png
    - assets/images/ic_settings.png
    - assets/images/ic_up_download.png
    - assets/images/ic_camera.png
    - assets/images/ic_cardin.png
    - assets/images/ic_acknowledge.png
    - assets/images/ic_scan_machine.png
    - assets/images/ic_complete.png
    - assets/images/ic_machine_available.png
    - assets/images/ic_machine_inuse.png
    - assets/images/ic_machine_offline.png
    - assets/images/ic_machine_reserved.png
    - assets/images/ic_arrow_up.png

    - assets/images/ic_task_complete.png
    - assets/images/ic_task_acknowledge.png
    - assets/images/ic_task_escalate.png
    - assets/images/ic_task_cardin.png
    - assets/images/ic_task_cancel.png

    - assets/images/2.0x/ic_complete.png
    - assets/images/2.0x/ic_cardin.png
    - assets/images/2.0x/ic_acknowledge.png
    - assets/images/2.0x/ic_scan_machine.png
    - assets/images/2.0x/ic_complete.png

    #TODO just temporairly
    - assets/json/TeamStatsCurrentDay.json
    - assets/json/UserStatsCurrentDay.json
    - assets/json/TeamStatsCurrentWeek.json
    - assets/json/UserStatsCurrentWeek.json
    - assets/json/TeamStatsCurrentMonth.json
    - assets/json/UserStatsCurrentMonth.json
    - assets/json/TeamTasksCompletedCurrentDay.json
    - assets/json/TeamTasksCompletedCurrentWeek.json
    - assets/json/TeamTasksCompletedCurrentMonth.json

#    - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: DigitalClock
      fonts:
        - asset: assets/fonts/DigitalClock.ttf

  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
