name: techviz
description: TechViz

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: ^0.11.3
  shared_preferences: ^0.4.2
  validator: ^0.0.7

  charts_flutter: ^0.3.0
  enumeration: ^0.0.2
  sqflite: any
  event_bus: ^1.0.1

#  vizexplorer_mobile_common:
#    git: http://git.colo.bis2.net/Mobile/Plugins/common.git

  vizexplorer_mobile_common:
    path: '../com.vizexplorer.mobile/common'

  dart_amqp:
    git: http://git.colo.bis2.net/Mobile/Plugins/dart_amqp.git

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

#  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/ic_about.png
    - assets/images/ic_alert.png
    - assets/images/ic_available_machine.png
    - assets/images/ic_down_arrow.png
    - assets/images/ic_duration.png
    - assets/images/ic_help.png
    - assets/images/ic_in_use.png
    - assets/images/ic_logout.png
    - assets/images/ic_my_profile.png
    - assets/images/ic_new_note.png
    - assets/images/ic_no_connection.png
    - assets/images/ic_note.png
    - assets/images/ic_offline_machine.png
    - assets/images/ic_out_of_service.png
    - assets/images/ic_processing.png
    - assets/images/ic_reserve.png
    - assets/images/ic_search.png
    - assets/images/ic_barcodescanner.png
    - assets/images/splash.png
    - assets/images/ic_settings.png
    - assets/images/ic_up_download.png
    - assets/images/ic_barcode.png
    - assets/images/ic_camera.png

#    - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: DigitalClock
      fonts:
        - asset: assets/fonts/DigitalClock.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
